namespace BCA.Network.Packets.Enums
{
    public enum CustomizationAchievementType
    {
        LevelUP,
        ELOUp,
        ELODown,
        RankedWin,
        SingleWin,
        MatchWin,
        TagWin,
        RankedLose,
        SingleLose,
        MatchLose,
        TagLose,
        GlobalDuelLose,
        GlobalDuelWin,
        RageQuit,
        GiveUp,
        BPAmount,
        PPAmount,
        PlayerSeniority,
        GlobalDuelMade,
        UnlockCards,
        SURPRISE,
        BuyAllBooster,
        AvatarCount,
        TitleCount,
        Event
    }
}
