using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCA.Network.Packets.Enums
{
    public enum PacketType
    {
        ChatMessage,
        Register,
        Login,
        AddHubPlayer,
        RemoveHubPlayer,
        PlayerList,
        CommandError,
        Kick,
        Ban,
        Banlist,
        EnabledAccount,
        DisabledAccount,
        Mute,
        PrivateMessage,
        Profil,
        UpdateCollection,
        DuelRequest,
        DuelRequestAnswer,
        DuelHost,
        DuelStart,
        DuelJoin,
        //DuelSeeker,
        UpdateRoom,
        AskBooster,
        PurchaseItem,
        Clear,
        MPAll,
        Panel,
        GivePoints,
        DonPoints,
        CardDonation,
        GiveCard,
        GiveAvatar,
        PanelUserlist,
        PanelUpdate,
        PanelAskProfile,
        Ranker,
        TradeRequest,
        TradeRequestAnswer,
        TradeMessage,
        TradeProposition,
        TradeExit,
        TradeAnswer,
        TradeEnd,
        ChangeAvatar,
        LoadAvatar,
        LoadBrocante,
        SellBrocanteCard,
        BuyBrocanteCard,
        CloseBrocante,
        AskSelectCard,
        SearchCard,
        BuyVIP,
        ChangeUsername,
        BuyAvatar,
        BuyTeam,
        BuyGreet,
        Help,
        Unban,
        Unmute,
        SpectatePlayer,
        GetBonus,
        DuelResult,
        AskTitle,
        ChangeTitle,
        GiveTitle,
        Maintenance,
        StopMaintenance,
        OfflineMessages,
        LoadPlayerCustomization
    }
}